# Generated by Django 4.1.2 on 2022-10-12 23:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='%Y/%m/%d/')),
                ('user_fk', models.ManyToManyField(related_name='user_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
